### ISSUE TITLE
Release on forge

### ISSUE THREAD

**Issue by oxc** [markt-de/puppet-postfix#14]
Please let me know when this module is released on the puppet forge under the new namespace, so I can deprecate the old module.

**Comment by fraenki** [comment]
https://forge.puppet.com/modules/markt/postfix/

Done :)

**Comment by oxc** [comment]
[oxc-postfix](https://forge.puppet.com/modules/oxc/postfix) is now deprecated ¯\_(ツ)_/¯

**Comment by oxc** [comment]
Thanks for taking this over!
